### ISSUE TITLE
What do I really need for my configuration?

### ISSUE THREAD

**Issue by Archorbtw** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#49]
Hello and sorry for the inconvenience,
I'm getting a computer for classes soon and would like to know what I can remove in the configuration to have a "light" Big Sur (which I will migrate to Monterey next).
I want to avoid weighing down my installation and have only the necessary.
Sorry again if I upset you. 🙏 
**Specs** : ThinkPad x250 / i5-5300u / Intel 7265AC / 8gb DDR3 SO-DIMM 1300MHz / SSD M.2 2422 256gb + SSD SATA 240gb (to have a Windows 11 and Arch multiboot)
PS : I don't have any options on my laptop if that helps 😅 
PS 2 : I would also like to know what is the point of having both open-source and proprietary drivers in the appropriate folder...   I saw for example that there was the OpenHfsPlus and HfsPlus file. Should I delete the one I don't want?
Thanks again 😓

**Comment by CLAY-BIOS** [comment]
> Hello and sorry for the inconvenience,
> I'm getting a computer for classes soon and would like to know what I can remove in the configuration to have a "light" Big Sur (which I will migrate to Monterey next).
> I want to avoid weighing down my installation and have only the necessary.
> Sorry again if I upset you. 🙏
> **Specs** : ThinkPad x250 / i5-5300u / Intel 7265AC / 8gb DDR3 SO-DIMM 1300MHz / SSD M.2 2422 256gb + SSD SATA 240gb (to have a Windows 11 and Arch multiboot)
> PS : I don't have any options on my laptop if that helps 😅
> PS 2 : I would also like to know what is the point of having both open-source and proprietary drivers in the appropriate folder... I saw for example that there was the OpenHfsPlus and HfsPlus file. Should I delete the one I don't want?
> Thanks again 😓

You mean to reduce the volume of EFI files? 
In EFI-> OC-> Drivers except OpenRuntime.efi, OpenCanopy.efi, AudioDxe.efi, OpenHfsPlus.efi, HfsPlus.efi, Files other than these five files can be deleted. 
![截屏2021-07-28 下午9 14 02](https://user-images.githubusercontent.com/54008255/127328364-9b34e94d-906c-4a60-9bac-8be60b3ee782.png)
In EFI-> OC-> Tools except CleanNvram.efi, ResetSystem.efi, OpenShell.efi, Files other than all three files can be deleted. 
![截屏2021-07-28 下午9 15 42](https://user-images.githubusercontent.com/54008255/127328557-cac37928-6159-41b4-b632-e3d0b67ea6fd.png)
The reason the EFI size is mainly because intel-Wi-Fi driven, There are four different versions of intel-Wi-Fi drivers in EFI-> OC-> Kexts, You just need to keep the driver for the corresponding version. 
![截屏2021-07-28 下午9 17 49](https://user-images.githubusercontent.com/54008255/127329044-8cb33f40-c873-4d88-921a-63bb7ea63aab.png)
OpenHfsPlus.efi has problems in earlier versions, So the HfsPlus.efi. is used The HfsPlus.efi and OpenHfsPlus.efi features are the same and I m just too lazy to modify it.

**Comment by Archorbtw** [comment]
Thanks again for the information!
It was exactly what I was looking for 👍 
Good luck to you 👋
